import re
import json
import base64
from io import BytesIO

from odoo import models, fields, api
from odoo.exceptions import ValidationError


class DeviceRegistry(models.Model):
    _name = 'device.registry'
    _description = 'Device Registry'
    _rec_name = 'device_name'
    _order = 'create_date desc'

    # ---------- Auto-filled by app scan ----------
    mac_address = fields.Char(
        string='Device ID',
        required=False,
        index=True,
        help='Auto-filled when the device scans the QR code shown on this page.',
    )
    device_name = fields.Char(
        string='Device Name',
        required=False,
        default='Pending',
        help='Auto-filled from the device model name when the app scans the QR.',
    )
    status = fields.Selection(
        selection=[
            ('pre_registered', 'Pre-Registered'),
            ('active', 'Active'),
            ('blocked', 'Blocked'),
        ],
        string='Status',
        default='pre_registered',
        required=True,
    )

    # ---------- Auto-filled when device connects ----------
    device_id = fields.Char(
        string='Device UUID',
        index=True,
        readonly=True,
        help='UUID generated by the app, linked on first activation.',
    )
    base_url = fields.Char(
        string='Base URL',
        readonly=True,
        help='Server URL used by this device.',
    )
    database_name = fields.Char(
        string='Database Name',
        readonly=True,
        help='Odoo database this device is connected to.',
    )
    last_login = fields.Datetime(
        string='Last Login',
        readonly=True,
    )

    # ---------- QR code — includes record ID so scan updates THIS record ----------
    registration_qr_image = fields.Binary(
        string='Registration QR Code',
        compute='_compute_registration_qr_image',
        help='App scans this to fill Device ID and Name into this record.',
    )

    def _compute_registration_qr_image(self):
        try:
            import qrcode
            db = self.env.cr.dbname
            for rec in self:
                if not rec.id:
                    rec.registration_qr_image = False
                    continue
                # QR contains record ID so the scan updates THIS specific record
                qr_data = json.dumps({'a': 'ng_reg', 'd': db, 'rid': rec.id})
                qr = qrcode.QRCode(box_size=7, border=3)
                qr.add_data(qr_data)
                qr.make(fit=True)
                img = qr.make_image(fill_color='black', back_color='white')
                buf = BytesIO()
                img.save(buf, format='PNG')
                rec.registration_qr_image = base64.b64encode(buf.getvalue()).decode()
        except Exception:
            for rec in self:
                rec.registration_qr_image = False

    _sql_constraints = [
        ('mac_address_uniq',
         'UNIQUE(mac_address)',
         'This Device ID is already registered.'),
    ]

    @api.constrains('mac_address')
    def _check_device_id(self):
        for rec in self:
            if not rec.mac_address:
                continue
            val = rec.mac_address.strip()
            is_uuid = re.fullmatch(
                r'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}',
                val
            )
            is_mac = re.fullmatch(
                r'([0-9A-Fa-f]{2}[:\-]){5}[0-9A-Fa-f]{2}', val
            )
            is_plain = re.fullmatch(r'[A-Za-z0-9_\-]{4,64}', val)
            if not is_uuid and not is_mac and not is_plain:
                raise ValidationError(
                    'Device ID must be a UUID, a MAC address '
                    '(XX:XX:XX:XX:XX:XX), or a plain alphanumeric ID (4–64 chars).'
                )
