import re
import json
import base64
from io import BytesIO

from odoo import models, fields, api
from odoo.exceptions import ValidationError


class DeviceRegistry(models.Model):
    _name = 'device.registry'
    _description = 'Device Registry'
    _rec_name = 'device_name'
    _order = 'create_date desc'

    # ---------- Auto-filled by app scan ----------
    mac_address = fields.Char(
        string='Device ID',
        required=False,
        index=True,
        help='Auto-filled when the device scans the QR code shown on this page.',
    )
    device_name = fields.Char(
        string='Device Name',
        required=False,
        default='Pending',
        help='Auto-filled from the device model name when the app scans the QR.',
    )
    status = fields.Selection(
        selection=[
            ('pre_registered', 'Pre-Registered'),
            ('active', 'Active'),
            ('deactivated', 'Deactivated'),
            ('blocked', 'Blocked'),
        ],
        string='Status',
        default='pre_registered',
        required=True,
    )

    # ---------- Auto-filled when device connects ----------
    device_id = fields.Char(
        string='Device UUID',
        index=True,
        readonly=True,
        help='UUID generated by the app, linked on first activation.',
    )
    base_url = fields.Char(
        string='Base URL',
        readonly=True,
        help='Server URL used by this device.',
    )
    database_name = fields.Char(
        string='Database Name',
        readonly=True,
        help='Odoo database this device is connected to.',
    )
    last_login = fields.Datetime(
        string='Last Login',
        readonly=True,
    )
    last_deactivated = fields.Datetime(
        string='Last Deactivated',
        readonly=True,
        help='Set automatically when the device leaves its session '
             '(when the app re-enters Device Config).',
    )
    last_blocked = fields.Datetime(
        string='Last Blocked',
        readonly=True,
        help='Set automatically when this record is set to Blocked.',
    )
    awaiting_rescan = fields.Boolean(
        string='Awaiting Re-scan',
        default=False,
        copy=False,
        help='Set when a device is unblocked — its old QR is now invalid and the '
             'admin must tap New so the device can scan a fresh QR.',
    )
    serial_no = fields.Char(
        string='Serial No',
        readonly=True,
        copy=False,
        index=True,
        store=True,
        compute='_compute_serial_no',
        help='Unique serial per record/login (DEV-#####). '
             'Shown in the app block popup so an admin can locate this record.',
    )

    @api.depends('create_date')
    def _compute_serial_no(self):
        for rec in self:
            if rec.serial_no:
                continue
            rec.serial_no = ('DEV-%05d' % rec.id) if isinstance(rec.id, int) else False

    # ---------- QR code — includes record ID so scan updates THIS record ----------
    registration_qr_image = fields.Binary(
        string='Registration QR Code',
        compute='_compute_registration_qr_image',
        store=True,
        help='App scans this to fill Device ID and Name into this record.',
    )

    @api.depends('create_date')
    def _compute_registration_qr_image(self):
        try:
            import qrcode
            db = self.env.cr.dbname
            for rec in self:
                if not rec.id:
                    rec.registration_qr_image = False
                    continue
                # QR contains record ID so the scan updates THIS specific record
                qr_data = json.dumps({'a': 'ng_reg', 'd': db, 'rid': rec.id})
                qr = qrcode.QRCode(box_size=7, border=3)
                qr.add_data(qr_data)
                qr.make(fit=True)
                img = qr.make_image(fill_color='black', back_color='white')
                buf = BytesIO()
                img.save(buf, format='PNG')
                rec.registration_qr_image = base64.b64encode(buf.getvalue()).decode()
        except Exception:
            for rec in self:
                rec.registration_qr_image = False

    # NOTE: Device ID (mac_address) is intentionally NOT unique. Each session is
    # a fresh record (admin taps New → device scans the new QR), so one physical
    # device accumulates a history of records — one per session — each keeping its
    # own Last Deactivated time. The old UNIQUE(mac_address) constraint was removed.

    @api.constrains('mac_address')
    def _check_device_id(self):
        for rec in self:
            if not rec.mac_address:
                continue
            val = rec.mac_address.strip()
            is_uuid = re.fullmatch(
                r'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}',
                val
            )
            is_mac = re.fullmatch(
                r'([0-9A-Fa-f]{2}[:\-]){5}[0-9A-Fa-f]{2}', val
            )
            is_plain = re.fullmatch(r'[A-Za-z0-9_\-]{4,64}', val)
            if not is_uuid and not is_mac and not is_plain:
                raise ValidationError(
                    'Device ID must be a UUID, a MAC address '
                    '(XX:XX:XX:XX:XX:XX), or a plain alphanumeric ID (4–64 chars).'
                )

    def write(self, vals):
        # Stamp the block time whenever a record is set to Blocked.
        if vals.get('status') == 'blocked':
            vals.setdefault('last_blocked', fields.Datetime.now())
        return super().write(vals)

    def action_block(self):
        """Header button — block the device (live/active records)."""
        self.write({'status': 'blocked'})

    def action_unblock(self):
        """
        Header button — unblock the device *device-wide*. The OLD QR(s) are
        invalidated: every blocked record for this device id (including this one)
        becomes Deactivated, so scanning any old QR is rejected as 'used'. This
        record is flagged `awaiting_rescan` to show the "tap New and scan" banner.
        The admin must tap New to issue a fresh QR.
        """
        for rec in self:
            if rec.device_id:
                others = self.search([
                    ('device_id', '=', rec.device_id),
                    ('database_name', '=', rec.database_name),
                    ('status', '=', 'blocked'),
                    ('id', '!=', rec.id),
                ])
                if others:
                    others.write({'status': 'deactivated'})
            rec.write({'status': 'deactivated', 'awaiting_rescan': True})
