//src/api/services/endpoints.js

export const API_ENDPOINTS = {
    VIEW_PRODUCTS: '/viewProducts',
    VIEW_CATEGORIES: '/viewCategories',
    VIEW_WAREHOUSE: `/viewWarehouses`,
    VIEW_CUSTOMERS: '/viewCustomers',
    VIEW_QUOTATION: '/viewQuotation',
    VIEW_AUDITING: '/viewAuditing',
    VIEW_CUSTOMER_VISIT_LIST: '/viewCustomerVisitList',
    VIEW_MARKET_STUDY: '/viewMarketStudy',
    VIEW_INVENTORY_BOX_REQUEST: '/viewInventoryboxrequest',
    VIEW_ENQUIRY_REGISTER: '/viewEnquiryRegister',
    VIEW_LEAD: '/viewLead',
    VIEW_PIPELINE: '/viewPipeline',
    VIEW_MEETINGS: '/viewCustomerSchedule',
    VIEW_VISIT_PLAN: '/viewVisitPlan',
    VIEW_BOX_INSPECTION_REPORT: '/viewBoxInspectionReport',
    VIEW_NON_INSPECTED_BOX: '/viewNonInspectedBoxListing',
    VIEW_SERVICE: '/viewJobRegistration',
    VIEW_ATTENDANCE: '/viewAttendance',
    VIEW_SPARE_PARTS: '/viewSparePartsRequest',
    VIEW_KPI: '/viewKpiTasks',
    VIEW_PICKUP: '/viewJobBooking',
    VIEW_VEHICLES: '/viewVehicles',
    VIEW_DRIVERS: '/viewDrivers',
    VIEW_LOCATIONS: '/viewLocations',
    VIEW_PURCHASE_REQUISITION: '/viewPurchaseRequest',
    VIEW_PRICE: '/viewPriceEnquiry',
    VIEW_PURCHASE_ORDER: '/viewPurchaseOrder',
    VIEW_DELIVERY_NOTE: '/viewPurchaseOrderDeliveryNote',
    VIEW_VENDOR_BILL: '/viewVendorBill',
    VIEW_PAYMENT_MADE: '/viewPaymentMade',
};

export const DROP_DOWN_API_ENDPOINTS = {
    INVOICE: '/viewInvoice/invoice/invoice_dropdown',
    SALES_RETURN: '/viewReturn/return/return_dropdown?type=sales_return',
    PURCHASE_RETURN: '/viewReturn/return/return_dropdown?type=purchase_return',
    SERVICE_RETURN: '/viewServiceReturn/service_return/service_return_dropdown',
    STOCK_TRANSFER: '/viewStockTransfer/stock_transaction/stock_transaction_dropdown',
    SERVICE: '/viewJobRegistration/job_registration/dropdown',
    VENDOR_BILL: '/viewVendorBill/vendor_bill/vendor_bill_drop_down',
    EMPLOYEE_DROPDOWN: '/viewEmployees/employee_list/employee_dropdown',
    CUSTOMER_DROPDOWN: '/viewCustomers/customer_list/drop_down',
    DEPARTMENT_DROPDOWN: '/viewDepartments/department_list/department_dropdown',
    BRAND_DROPDOWN: '/viewBrands/brand_list/brand_dropdown',
    PURPOSE_OF_VISIT_DROPDOWN: '/viewCustomerPurposeOfVisit/customer_purpose_of_vist/customer_purpose_of_visit_dropdown',
    SITE_LOCATION_DROPDOWN: '/viewSiteLocation/site_location_list/site_location_dropdown',
    COUNTRY: "/viewCountry/country_list/country_dropdown",
    STATE: "/viewState",
    AREA: "/viewArea/area_list/drop_down",
    SALESPERSON: "/viewEmployees/employee_list/employee_dropdown",
    COLLECTIONAGENT: "/viewEmployees/employee_list/employee_dropdown",
    LANGUAGE: "/viewLanguage/language_list/language_dropdown",
    CURRENCY: "/viewCurrency/currency_list/currency_dropdown",
    SOURCE: "/viewSource/source_list/source_dropdown",
    OPPORTUNITY: "/viewOppertunityType/oppertunity_list/oppertunity_dropdown",
    ENQUIRY_TYPE: "/viewEnquiryType/enquiry_list/enquiry_dropdown",
    NON_INSPECTED: "/viewNonInspectedBoxListing",
    PRODUCTS: "/viewProducts/product_list/product_dropdown",
    UOM: "/viewUnitOfMeasure",
    CUSTOMER_NAME: "/viewCustomers/customer_list/drop_down",
    WAREHOUSE: "/viewWarehouses/warehouse_list/warehouse_dropdown",
    DEVICE: "/viewJobDevice/job_devices/dropdown",
    BRAND: "/viewJobBrand/job_brand_model/dropdown",
    CONSUMER_MODEL: "/viewJobConsumerModel/job_consumer_model/dropdown",
    ASSIGNED_TO: "/viewEmployees/employee_list/employee_dropdown",
    ACCESSORIES: "/viewJobAccessory/accessory_list/accessory_dropdown",
    COMPLAINTS: "/viewServiceRegisterSubProblem/service_register_sub_problem_list/service_register_sub_problem_dropdown",
    SUB_COMPLAINTS: "/viewServiceRegisterSubProblem/service_register_sub_problem_list/service_register_sub_problem_dropdown",
    UNIT_OF_MEASURE: "/viewUnitOfMeasure/quality_list/quality_dropdown",
    TAXES: "/viewTaxType/tax_type_list/tax_type_dropdown",
    PAYMENT_MODE: "/viewPaymentMethod/payment_method_list/payment_method_dropdown",
    SUPPLIERS: "/viewsupplier",
    BANK_CHEQUE: "/viewChequeBank/cheq_bank_list/cheq_bank_dropdown",
};


export const DETAIL_API_ENDPOINTS = {
    // Transaction Auditing ENDPOINTS
    GET_INVOICE_DETAILS: '/viewInvoice',
    GET_VENDOR_DETAILS: '/viewVendorBill',
    GET_SALES_RETURN_DETAILS: '/viewReturn',
    GET_PURCHASE_RETURN_DETAILS: '/viewReturn',
    GET_CAPITAL_PAYMENT_DETAILS: '/viewCapitalPayment',
    GET_JOB_INVOICE_DETAILS: '/viewJobInvoice',
    GET_SPARE_PARTS_ISSUE_DETAILS: '/viewSparePartsIssue',
    GET_SPARE_PARTS_ISSUE_AUDIT_DETAILS: '/viewSparePartsIssue/auditing/spare_parts_issue_details',
    GET_PETTY_CASH_ALLOTMENT_DETAILS: '/viewPettyCashAllotement',
    GET_PETTY_CASH_EXPENSE_DETAILS: '/viewPettyCashExpence',
    GET_PETTY_CASH_TRANSFER_DETAILS: '/viewPettyCashTransfer',
    GET_PETTY_CASH_RETURN_DETAILS: '/viewPettyCashReturn',
    GET_CAPITAL_RECEIPTS_DETAILS: '/viewCapital',
    GET_CUSTOMER_RECEIPTS_DETAILS: '/viewRegisterPayment',
    GET_CUSTOMER_PAYMENT_DETAILS: '/viewCustomerPayment',
    GET_CASH_RECEIPTS_DETAILS: '/viewCapital',
    GET_CASH_PAYMENTS_DETAILS: '/viewExpense',
    GET_EXPENSE_DETAILS: '/viewExpense',
    GET_SUPPLIER_RECEIPTS_DETAILS: '/viewSupplierReceipt',
    GET_SUPPLIER_PAYMENTS_DETAILS: '/viewPaymentMade',
    GET_LEDGER_TYPE_DETAILS: '/viewMasterLedger',
    GET_SALARY_PAYMENT_DETAILS: '/viewSalaryPayment',
    GET_SALARY_ADVANCE_PAYMENT_DETAILS: '/viewSalaryAdvance',
    GET_COLLECTION_TYPE_DETAILS: '/viewCollectionType',
    GET_CHEQUE_LEDGER: '/viewChequeLedger',
    GET_STOCK_TRANSFER_DETAILS: '/viewStockTransfer',
    GET_FUND_TRANSFER_DETAILS: '/viewFundTransfer',
    GET_INVENTORY_DETAILS: 'https://317099813597.ngrok-free.app/api/viewInventory',
    GET_PRODUCT_DETAILS: '/viewProducts',
    // Vehicle Tracking endpoints
    GET_VEHICLES_DETAILS: '/viewVehicles',
    GET_DRIVERS_DETAILS: '/viewDrivers',
    GET_LOCATIONS_DETAILS: '/viewLocations',
    
    // latest updates keys
    GET_JOB_REGISTER_PAYMENT_DETAILS: '/viewJobRegisterPayment',
    GET_SERVICE_RETURN_DETAILS: '/viewServiceReturn/service_return/service_return_dropdown',
    GET_PAYMENT_RECEIPT_DETAILS: '/viewJobRegisterPayment',
};